/**
 * aura-sounds.js — Aura Languages
 * Sistema de sonidos sintéticos con Web Audio API.
 * Sin archivos externos — síntesis matemática pura.
 * Uso: AuraSounds.play('nombre-del-sonido')
 */
(function () {
  'use strict';
  var _ctx = null, _masterGain = null, _boost = null, _enabled = true, _volume = 1.0;
  function _getCtx() {
    if (!_ctx) {
      _ctx = new (window.AudioContext || window.webkitAudioContext)();
      _masterGain = _ctx.createGain();
      _masterGain.gain.value = _volume;
      _boost = _ctx.createGain();
      _boost.gain.value = 3.5;
      _masterGain.connect(_boost);
      _boost.connect(_ctx.destination);
    }
    if (_ctx.state === 'suspended') _ctx.resume();
    return _ctx;
  }
  function _osc(c, type, freq) { var o = c.createOscillator(); o.type = type; o.frequency.value = freq; return o; }
  function _gain(c, val) { var g = c.createGain(); g.gain.value = val; return g; }
  var _sounds = {
    'word-place': function(c,t){ var o=_osc(c,'sine',220),g=_gain(c,0),f=c.createBiquadFilter(); f.type='lowpass'; f.frequency.value=500; o.connect(f); f.connect(g); g.connect(_masterGain); o.frequency.exponentialRampToValueAtTime(160,t+0.3); g.gain.setValueAtTime(0,t); g.gain.linearRampToValueAtTime(0.2,t+0.04); g.gain.exponentialRampToValueAtTime(0.001,t+0.32); o.start(t); o.stop(t+0.35); },
    'correct': function(c,t){ var o1=_osc(c,'sine',329),g1=_gain(c,0); o1.connect(g1); g1.connect(_masterGain); g1.gain.setValueAtTime(0,t); g1.gain.linearRampToValueAtTime(0.2,t+0.08); g1.gain.exponentialRampToValueAtTime(0.001,t+0.9); o1.start(t); o1.stop(t+0.95); var o2=_osc(c,'sine',440),g2=_gain(c,0); o2.connect(g2); g2.connect(_masterGain); o2.frequency.linearRampToValueAtTime(523,t+0.35); g2.gain.setValueAtTime(0,t+0.1); g2.gain.linearRampToValueAtTime(0.16,t+0.22); g2.gain.exponentialRampToValueAtTime(0.001,t+0.95); o2.start(t+0.1); o2.stop(t+1.0); },
    'wrong': function(c,t){ var o=_osc(c,'sawtooth',180),g=_gain(c,0.15),f=c.createBiquadFilter(); f.type='lowpass'; f.frequency.value=300; o.connect(f); f.connect(g); g.connect(_masterGain); o.frequency.exponentialRampToValueAtTime(80,t+0.28); g.gain.exponentialRampToValueAtTime(0.001,t+0.3); o.start(t); o.stop(t+0.32); },
    'combo': function(c,t){ var o=_osc(c,'sine',200),g=_gain(c,0); o.connect(g); g.connect(_masterGain); o.frequency.exponentialRampToValueAtTime(420,t+0.45); g.gain.setValueAtTime(0,t); g.gain.linearRampToValueAtTime(0.2,t+0.06); g.gain.setValueAtTime(0.2,t+0.38); g.gain.exponentialRampToValueAtTime(0.001,t+0.58); o.start(t); o.stop(t+0.62); },
    'score-tick': function(c,t){ [[196,0],[247,0.2],[294,0.4]].forEach(function(p){ var o=_osc(c,'sine',p[0]),g=_gain(c,0); o.connect(g); g.connect(_masterGain); g.gain.setValueAtTime(0,t+p[1]); g.gain.linearRampToValueAtTime(0.18,t+p[1]+0.06); g.gain.exponentialRampToValueAtTime(0.001,t+p[1]+0.5); o.start(t+p[1]); o.stop(t+p[1]+0.55); }); },
    'result-fanfare': function(c,t){ var bass=_osc(c,'sine',130),bg=_gain(c,0); bass.connect(bg); bg.connect(_masterGain); bg.gain.setValueAtTime(0,t); bg.gain.linearRampToValueAtTime(0.3,t+0.05); bg.gain.exponentialRampToValueAtTime(0.001,t+1.4); bass.start(t); bass.stop(t+1.45); [[196,0,0.22],[247,0.05,0.2],[329,0.1,0.18]].forEach(function(p){ var o=_osc(c,'sine',p[0]),g=_gain(c,0); o.connect(g); g.connect(_masterGain); g.gain.setValueAtTime(0,t+p[1]); g.gain.linearRampToValueAtTime(p[2],t+p[1]+0.12); g.gain.exponentialRampToValueAtTime(0.001,t+p[1]+1.35); o.start(t+p[1]); o.stop(t+p[1]+1.4); }); var sh=_osc(c,'sine',523),sg=_gain(c,0); sh.connect(sg); sg.connect(_masterGain); sg.gain.setValueAtTime(0,t+0.2); sg.gain.linearRampToValueAtTime(0.1,t+0.4); sg.gain.exponentialRampToValueAtTime(0.001,t+1.4); sh.start(t+0.2); sh.stop(t+1.45); },
    'ui-click': function(c,t){ var o=_osc(c,'sine',600),g=_gain(c,0.08); o.connect(g); g.connect(_masterGain); o.frequency.exponentialRampToValueAtTime(300,t+0.06); g.gain.exponentialRampToValueAtTime(0.001,t+0.07); o.start(t); o.stop(t+0.08); },
    'scene-swoosh': function(c,t){ var o=_osc(c,'sine',200),g=_gain(c,0),f=c.createBiquadFilter(); f.type='bandpass'; f.frequency.value=400; f.Q.value=0.8; o.connect(f); f.connect(g); g.connect(_masterGain); o.frequency.exponentialRampToValueAtTime(600,t+0.22); g.gain.setValueAtTime(0,t); g.gain.linearRampToValueAtTime(0.15,t+0.05); g.gain.exponentialRampToValueAtTime(0.001,t+0.28); o.start(t); o.stop(t+0.3); },
    'line-correct': function(c,t){ var o=_osc(c,'sine',523),g=_gain(c,0); o.connect(g); g.connect(_masterGain); g.gain.setValueAtTime(0,t); g.gain.linearRampToValueAtTime(0.2,t+0.015); g.gain.exponentialRampToValueAtTime(0.001,t+1.4); o.start(t); o.stop(t+1.45); },
    'error-tick': function(c,t){ var o=_osc(c,'sine',400),g=_gain(c,0); o.connect(g); g.connect(_masterGain); o.frequency.exponentialRampToValueAtTime(200,t+0.12); g.gain.setValueAtTime(0,t); g.gain.linearRampToValueAtTime(0.1,t+0.02); g.gain.exponentialRampToValueAtTime(0.001,t+0.14); o.start(t); o.stop(t+0.16); },
    'line-shift': function(c,t){ var o=_osc(c,'sine',440),g=_gain(c,0); o.connect(g); g.connect(_masterGain); g.gain.setValueAtTime(0,t); g.gain.linearRampToValueAtTime(0.06,t+0.01); g.gain.exponentialRampToValueAtTime(0.001,t+0.07); o.start(t); o.stop(t+0.08); },
    'gameover': function(c,t){ [[110,0],[138,0.1],[165,0.2]].forEach(function(p){ var o=_osc(c,'sine',p[0]),g=_gain(c,0); o.connect(g); g.connect(_masterGain); g.gain.setValueAtTime(0,t+p[1]); g.gain.linearRampToValueAtTime(0.42,t+p[1]+0.2); g.gain.setValueAtTime(0.42,t+p[1]+0.6); g.gain.exponentialRampToValueAtTime(0.001,t+p[1]+1.7); o.start(t+p[1]); o.stop(t+p[1]+1.8); }); var o2=_osc(c,'sine',220),g2=_gain(c,0); o2.connect(g2); g2.connect(_masterGain); g2.gain.setValueAtTime(0,t+0.15); g2.gain.linearRampToValueAtTime(0.12,t+0.35); g2.gain.exponentialRampToValueAtTime(0.001,t+1.8); o2.start(t+0.15); o2.stop(t+1.85); },
    'levelup': function(c,t){ [[196,0,0.22],[247,0.12,0.18],[329,0.25,0.16]].forEach(function(p){ var o=_osc(c,'sine',p[0]),g=_gain(c,0); o.connect(g); g.connect(_masterGain); g.gain.setValueAtTime(0,t+p[1]); g.gain.linearRampToValueAtTime(p[2],t+p[1]+0.18); g.gain.exponentialRampToValueAtTime(0.001,t+p[1]+1.0); o.start(t+p[1]); o.stop(t+p[1]+1.05); }); var sh=_osc(c,'sine',523),sg=_gain(c,0); sh.connect(sg); sg.connect(_masterGain); sg.gain.setValueAtTime(0,t+0.5); sg.gain.linearRampToValueAtTime(0.1,t+0.7); sg.gain.exponentialRampToValueAtTime(0.001,t+1.2); sh.start(t+0.5); sh.stop(t+1.25); },
    'mic-on': function(c,t){ var o=_osc(c,'sine',330),g=_gain(c,0); o.connect(g); g.connect(_masterGain); o.frequency.linearRampToValueAtTime(370,t+0.4); g.gain.setValueAtTime(0,t); g.gain.linearRampToValueAtTime(0.14,t+0.15); g.gain.setValueAtTime(0.14,t+0.3); g.gain.exponentialRampToValueAtTime(0.001,t+0.65); o.start(t); o.stop(t+0.68); },
    'cd-tick': function(c,t,opts){ var isLast=opts&&opts.last, freq=isLast?900:700, vol=isLast?0.2:0.12, o=_osc(c,'sine',freq),g=_gain(c,0); o.connect(g); g.connect(_masterGain); g.gain.setValueAtTime(0,t); g.gain.linearRampToValueAtTime(vol,t+0.01); g.gain.exponentialRampToValueAtTime(0.001,t+0.07); o.start(t); o.stop(t+0.08); },
    'retry': function(c,t){ [294,370,440].forEach(function(f){ var o=_osc(c,'sine',f),g=_gain(c,0); o.connect(g); g.connect(_masterGain); g.gain.setValueAtTime(0,t); g.gain.linearRampToValueAtTime(0.12,t+0.15); g.gain.setValueAtTime(0.12,t+0.3); g.gain.exponentialRampToValueAtTime(0.001,t+0.7); o.start(t); o.stop(t+0.75); }); },
    'card-flip': function(c,t){ var o=_osc(c,'sine',800),g=_gain(c,0),f=c.createBiquadFilter(); f.type='highpass'; f.frequency.value=300; o.connect(f); f.connect(g); g.connect(_masterGain); o.frequency.exponentialRampToValueAtTime(200,t+0.15); g.gain.setValueAtTime(0,t); g.gain.linearRampToValueAtTime(0.12,t+0.02); g.gain.exponentialRampToValueAtTime(0.001,t+0.17); o.start(t); o.stop(t+0.2); },
    'session-start': function(c,t){ var sub=_osc(c,'sine',98),sg=_gain(c,0); sub.connect(sg); sg.connect(_masterGain); sg.gain.setValueAtTime(0,t); sg.gain.linearRampToValueAtTime(0.32,t+0.55); sg.gain.setValueAtTime(0.32,t+0.9); sg.gain.exponentialRampToValueAtTime(0.001,t+2.5); sub.start(t); sub.stop(t+2.6); [[147,0.3,0.18],[196,0.55,0.16],[247,0.85,0.12]].forEach(function(p){ [p[0],p[0]+1.2].forEach(function(freq,i){ var o=_osc(c,'sine',freq),g=_gain(c,0); o.connect(g); g.connect(_masterGain); g.gain.setValueAtTime(0,t+p[1]); g.gain.linearRampToValueAtTime(i===0?p[2]:p[2]*0.5,t+p[1]+0.45); g.gain.exponentialRampToValueAtTime(0.001,t+p[1]+2.2); o.start(t+p[1]); o.stop(t+p[1]+2.3); }); }); var cr=_osc(c,'sine',784),cg=_gain(c,0); cr.connect(cg); cg.connect(_masterGain); cg.gain.setValueAtTime(0,t+1.5); cg.gain.linearRampToValueAtTime(0.06,t+1.85); cg.gain.exponentialRampToValueAtTime(0.001,t+3.1); cr.start(t+1.5); cr.stop(t+3.2); },
    'tab-switch': function(c,t){ var o=_osc(c,'sine',800),g=_gain(c,0); o.connect(g); g.connect(_masterGain); o.frequency.exponentialRampToValueAtTime(500,t+0.08); g.gain.setValueAtTime(0,t); g.gain.linearRampToValueAtTime(0.1,t+0.01); g.gain.exponentialRampToValueAtTime(0.001,t+0.09); o.start(t); o.stop(t+0.1); },
    'submit-send': function(c,t){ var o=_osc(c,'sine',200),g=_gain(c,0),f=c.createBiquadFilter(); f.type='bandpass'; f.frequency.value=600; f.Q.value=1.2; o.connect(f); f.connect(g); g.connect(_masterGain); o.frequency.exponentialRampToValueAtTime(1200,t+0.25); g.gain.setValueAtTime(0,t); g.gain.linearRampToValueAtTime(0.15,t+0.06); g.gain.exponentialRampToValueAtTime(0.001,t+0.28); o.start(t); o.stop(t+0.3); },
    'section-done': function(c,t){ [[196,0],[247,0.06],[294,0.12]].forEach(function(p){ var o=_osc(c,'sine',p[0]),g=_gain(c,0); o.connect(g); g.connect(_masterGain); g.gain.setValueAtTime(0,t+p[1]); g.gain.linearRampToValueAtTime(0.15,t+p[1]+0.1); g.gain.setValueAtTime(0.15,t+p[1]+0.2); g.gain.exponentialRampToValueAtTime(0.001,t+p[1]+0.5); o.start(t+p[1]); o.stop(t+p[1]+0.55); }); },
    'rank-up': function(c,t){ var bass=_osc(c,'sine',98),bg=_gain(c,0); bass.connect(bg); bg.connect(_masterGain); bg.gain.setValueAtTime(0,t); bg.gain.linearRampToValueAtTime(0.35,t+0.15); bg.gain.exponentialRampToValueAtTime(0.001,t+1.8); bass.start(t); bass.stop(t+1.9); [[196,0.2,2.2],[294,0.45,1.9],[392,0.7,1.7]].forEach(function(p){ var o=_osc(c,'sine',p[0]),g=_gain(c,0); o.connect(g); g.connect(_masterGain); g.gain.setValueAtTime(0,t+p[1]); g.gain.linearRampToValueAtTime(0.18,t+p[1]+0.25); g.gain.exponentialRampToValueAtTime(0.001,t+p[1]+p[2]); o.start(t+p[1]); o.stop(t+p[1]+p[2]+0.1); }); var sh=_osc(c,'sine',784),sg=_gain(c,0); sh.connect(sg); sg.connect(_masterGain); sg.gain.setValueAtTime(0,t+1.1); sg.gain.linearRampToValueAtTime(0.06,t+1.5); sg.gain.exponentialRampToValueAtTime(0.001,t+2.6); sh.start(t+1.1); sh.stop(t+2.7); },
    'exam-fail': function(c,t){ [[196,98,0,0.26],[147,73,0.1,0.2]].forEach(function(p){ var o=_osc(c,'sine',p[0]),g=_gain(c,0); o.connect(g); g.connect(_masterGain); o.frequency.setValueAtTime(p[0],t+p[2]); o.frequency.exponentialRampToValueAtTime(p[1],t+p[2]+0.9); g.gain.setValueAtTime(0,t+p[2]); g.gain.linearRampToValueAtTime(p[3],t+p[2]+0.12); g.gain.setValueAtTime(p[3],t+p[2]+0.2); g.gain.exponentialRampToValueAtTime(0.001,t+p[2]+1.1); o.start(t+p[2]); o.stop(t+p[2]+1.15); }); },
    'streak-popup': function(c,t){ var o=_osc(c,'sine',180),g=_gain(c,0); o.connect(g); g.connect(_masterGain); g.gain.setValueAtTime(0,t); g.gain.linearRampToValueAtTime(0.22,t+0.5); g.gain.setValueAtTime(0.22,t+0.65); g.gain.exponentialRampToValueAtTime(0.001,t+1.5); o.start(t); o.stop(t+1.55); var o2=_osc(c,'sine',360),g2=_gain(c,0); o2.connect(g2); g2.connect(_masterGain); g2.gain.setValueAtTime(0,t+0.25); g2.gain.linearRampToValueAtTime(0.09,t+0.65); g2.gain.exponentialRampToValueAtTime(0.001,t+1.5); o2.start(t+0.25); o2.stop(t+1.55); },
    'claim-reward': function(c,t){ [[130,0,0.22],[196,0.15,0.18],[261,0.32,0.14]].forEach(function(p){ var o=_osc(c,'sine',p[0]),g=_gain(c,0); o.connect(g); g.connect(_masterGain); g.gain.setValueAtTime(0,t+p[1]); g.gain.linearRampToValueAtTime(p[2],t+p[1]+0.18); g.gain.setValueAtTime(p[2],t+p[1]+0.28); g.gain.exponentialRampToValueAtTime(0.001,t+p[1]+0.8); o.start(t+p[1]); o.stop(t+p[1]+0.85); }); var sh=_osc(c,'sine',523),sg=_gain(c,0); sh.connect(sg); sg.connect(_masterGain); sg.gain.setValueAtTime(0,t+0.55); sg.gain.linearRampToValueAtTime(0.09,t+0.75); sg.gain.exponentialRampToValueAtTime(0.001,t+1.2); sh.start(t+0.55); sh.stop(t+1.25); },
    'level-up': function(c,t){ [[165,0,0.22],[220,0.08,0.18],[330,0.18,0.13]].forEach(function(p){ var o=_osc(c,'sine',p[0]),g=_gain(c,0); o.connect(g); g.connect(_masterGain); g.gain.setValueAtTime(0,t+p[1]); g.gain.linearRampToValueAtTime(p[2],t+p[1]+0.35); g.gain.setValueAtTime(p[2],t+p[1]+0.5); g.gain.exponentialRampToValueAtTime(0.001,t+p[1]+1.5); o.start(t+p[1]); o.stop(t+p[1]+1.55); }); var sh=_osc(c,'sine',660),sg=_gain(c,0); sh.connect(sg); sg.connect(_masterGain); sg.gain.setValueAtTime(0,t+0.6); sg.gain.linearRampToValueAtTime(0.07,t+0.9); sg.gain.exponentialRampToValueAtTime(0.001,t+1.6); sh.start(t+0.6); sh.stop(t+1.65); },
    'save-confirm': function(c,t){ [[220,0,0.18],[330,0.08,0.13]].forEach(function(p){ var o=_osc(c,'sine',p[0]),g=_gain(c,0); o.connect(g); g.connect(_masterGain); g.gain.setValueAtTime(0,t+p[1]); g.gain.linearRampToValueAtTime(p[2],t+p[1]+0.08); g.gain.setValueAtTime(p[2],t+p[1]+0.15); g.gain.exponentialRampToValueAtTime(0.001,t+p[1]+0.65); o.start(t+p[1]); o.stop(t+p[1]+0.7); }); },
    'locked': function(c,t){ [[330,220,0,0.16],[247,165,0.05,0.1]].forEach(function(p){ var o=_osc(c,'sine',p[0]),g=_gain(c,0); o.connect(g); g.connect(_masterGain); o.frequency.setValueAtTime(p[0],t+p[2]); o.frequency.exponentialRampToValueAtTime(p[1],t+p[2]+0.35); g.gain.setValueAtTime(0,t+p[2]); g.gain.linearRampToValueAtTime(p[3],t+p[2]+0.06); g.gain.exponentialRampToValueAtTime(0.001,t+p[2]+0.48); o.start(t+p[2]); o.stop(t+p[2]+0.5); }); },
    'life-lost': function(c,t){ [[185,98,0,0.28],[123,73,0.05,0.16]].forEach(function(p){ var o=_osc(c,'sine',p[0]),g=_gain(c,0); o.connect(g); g.connect(_masterGain); o.frequency.setValueAtTime(p[0],t+p[2]); o.frequency.exponentialRampToValueAtTime(p[1],t+p[2]+0.55); g.gain.setValueAtTime(0,t+p[2]); g.gain.linearRampToValueAtTime(p[3],t+p[2]+0.07); g.gain.setValueAtTime(p[3],t+p[2]+0.12); g.gain.exponentialRampToValueAtTime(0.001,t+p[2]+0.65); o.start(t+p[2]); o.stop(t+p[2]+0.7); }); }
  };

  window.AuraSounds = {
    play: function(name, opts) {
      if (!_enabled) return;
      try { var fn=_sounds[name]; if(!fn) return; var c=_getCtx(); fn(c,c.currentTime,opts); } catch(e) {}
    },
    setVolume: function(v) { _volume=Math.max(0,Math.min(1,v)); if(_masterGain) _masterGain.gain.value=_volume; },
    setEnabled: function(v) { _enabled=!!v; },
    isEnabled: function() { return _enabled; }
  };

  function _wake() { if(_ctx && _ctx.state==='suspended') _ctx.resume(); }
  document.addEventListener('touchstart', _wake, { once: true });
  document.addEventListener('click', _wake, { once: true });
})();
