[build]
  publish = "."

[build.processing.html]
  pretty_urls = true

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
