services:
  - type: web
    name: aura-stream-api
    env: node
    rootDir: stream-api
    buildCommand: npm install && pip3 install -U youtube-transcript-api
    startCommand: node server.js
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: GH_TOKEN
        sync: false
